# -*- coding: utf-8 -*-
"""Complex-Text-to-Visual Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hoXh_ZauLoo0vJxoit5JIbR_j64mtCOD
"""

# Cell 1: Installs
!pip install crewai openai --quiet

# Cell 2: Imports & API Key
import os
from openai import OpenAI
from google.colab import userdata
from crewai import Agent, Task, Crew, Process
from crewai.tools import BaseTool
from IPython.display import Image, display, Markdown

# --- Setup: Get API Key from Colab Secrets ---
try:
    OPENAI_API_KEY = userdata.get('OPENAI_API_KEY')
    os.environ['OPENAI_API_KEY'] = OPENAI_API_KEY
    client = OpenAI(api_key=OPENAI_API_KEY)
    print("OpenAI API key loaded and environment set.")
except Exception as e:
    print(f"Error loading API key: {e}")

# Cell 3: Define Custom Tool (Corrected)
class VisualSimplifierTool(BaseTool):
    name: str = "Complex Text to Visual Tool"
    description: str = "Takes a block of complex text and generates a visual explanation (diagram, infographic) using a two-step AI process. Returns the URL of the generated image."

    def _run(self, complex_text: str) -> str:
        print(f"--- Tool: Simplifying text and generating visual... ---")

        # --- Step 1: Simplify & Create DALL-E Prompt (Our logic from before) ---
        try:
            simplification_prompt = f"""
            You are a visual learning designer.
            Read the following complex text and extract the key concepts.
            Your goal is to generate a *prompt* for DALL-E 3 to create a simple, clear
            visual diagram or infographic that explains this concept.

            The DALL-E 3 prompt should:
            1. Be detailed and specific.
            2. Request a style, e.g., 'a simple diagram', 'a clean infographic'.
            3. Include labels for the key parts.

            Complex Text:
            "{complex_text}"

            Respond with *only* the DALL-E 3 prompt and nothing else.
            """

            response = client.chat.completions.create(
                model="gpt-4o",
                messages=[{"role": "user", "content": simplification_prompt}],
                max_tokens=300
            )
            dalle_prompt = response.choices[0].message.content

            # --- THIS PRINT IS REMOVED TO PREVENT THE LOGGING CRASH ---
            # print(f"\n--- Generated DALL-E Prompt ---\n{dalle_prompt}")

            # --- Step 2: Generate Visual (Our logic from before) ---
            print("\n--- Generating visual with DALL-E 3... ---")
            image_response = client.images.generate(
                model="dall-e-3",
                prompt=dalle_prompt,
                size="1024x1024",
                quality="standard",
                n=1,
            )

            image_url = image_response.data[0].url
            return image_url

        except Exception as e:
            return f"Error in visual generation process: {e}"

# Instantiate the tool
visual_simplifier_tool = VisualSimplifierTool()

# Cell 4: Create Your Agent
visual_simplifier_agent = Agent(
    role='Visual Simplifier',
    goal='Create a clear and simple visual explanation (diagram, infographic, or concept map) from a block of complex text.',
    backstory=(
        'You are an expert in instructional design and cognitive science. '
        'You know how to break down complex topics into easy-to-understand visual metaphors and diagrams.'
    ),
    tools=[visual_simplifier_tool],
    verbose=True,
    allow_delegation=False
)

# Cell 5: Define The Task
# Let's use the same complex text from our test
''' complex_text_input = """
Photosynthesis is a process used by plants and other organisms to convert light
energy into chemical energy, through a process that converts carbon dioxide
and water into sugars (glucose) and oxygen. This process is crucial for
life on Earth as it provides the oxygen we breathe and the
energy at the base of most food chains. It occurs in
chloroplasts, which contain the pigment chlorophyll.
""" '''

complex_text_input = "A high-resolution, photorealistic image of a red Mustang sports car driving on a coastal road at sunset."

simplification_task = Task(
    description=(
        'Use your tool to convert the following complex text into a single visual explanation. '
        f'Here is the text:\n\n"{complex_text_input}"'
    ),
    expected_output='The final URL of the generated visual diagram.',
    agent=visual_simplifier_agent
)

# Cell 6: Run Your Crew! (Corrected for CrewOutput.raw)
# Setup the crew
visual_crew = Crew(
    agents=[visual_simplifier_agent],
    tasks=[simplification_task],
    process=Process.sequential,
    verbose=False # Keep this False to prevent the other logging bug
)

# Kick off the crew
print("\n--- Kicking off Visual Simplification Crew ---")
crew_result = visual_crew.kickoff()

print("\n--- Crew Finished ---")
print("Full Crew Output Object:")
print(crew_result)

# Display the final image output
print("\nDisplaying final visual explanation:")

# --- START OF FIX ---
# The final string is in the .raw attribute
if crew_result and crew_result.raw and crew_result.raw.startswith('http'):
    # We display crew_result.raw
    display(Image(url=crew_result.raw))
else:
    # Print the whole object for debugging if it failed
    print(f"Crew returned an error or unexpected result: {crew_result}")
# --- END OF FIX ---