# -*- coding: utf-8 -*-
"""Image-to-Audio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TRtgKmcOf2cqRkP8LKMgjo2JV-XijPi5
"""



# Cell 2: Imports & API Key
import os
import base64
from openai import OpenAI
from google.colab import userdata
from crewai import Agent, Task, Crew, Process
from crewai.tools import BaseTool

# --- Setup: Get API Key from Colab Secrets ---
try:
    OPENAI_API_KEY = userdata.get('OPENAI_API_KEY')
    os.environ['OPENAI_API_KEY'] = OPENAI_API_KEY
    client = OpenAI(api_key=OPENAI_API_KEY)
    print("OpenAI API key loaded and environment set.")
except Exception as e:
    print(f"Error loading API key: {e}")

# --- Helper Function (from our last step) ---
def encode_image(image_path):
    """Encodes an image file to a base64 string."""
    with open(image_path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode('utf-8')

# Cell 3: Define Custom Tools (Corrected)
class VisualTools(BaseTool):
    name: str = "Image Description Tool"
    description: str = "Takes the file path of an image and generates brief, standard, and detailed descriptions using GPT-4o vision."

    def _run(self, image_path: str) -> str:
        # This is the same logic from our working script
        print(f"--- Tool: Running Visual Analysis for {image_path} ---")
        base64_image = encode_image(image_path)

        try:
            response = client.chat.completions.create(
                model="gpt-4o",
                messages=[
                    {
                        "role": "user",
                        "content": [
                            # This prompt is based on your project doc
                            {"type": "text", "text": "Describe this image in detail. Follow W3C WAI guidelines. Provide three versions: a 'Brief' description, a 'Standard' description, and a 'Detailed' description."},
                            {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base66,{base64_image}"}}
                        ]
                    }
                ],
                max_tokens=500
            )
            description_text = response.choices[0].message.content
            return description_text
        except Exception as e:
            return f"Error analyzing image: {e}"

class AudioTools(BaseTool):
    name: str = "Text-to-Speech Tool"
    description: str = "Takes a string of text and a save path, converts the text to an MP3 audio file, and saves it."

    def _run(self, text_to_speak: str, save_path: str = "crew_output_audio.mp3") -> str:
        # This is the same logic from our working script
        print(f"--- Tool: Generating Audio for text... ---")
        try:
            audio_response = client.audio.speech.create(
                model="tts-1",
                voice="nova",
                input=text_to_speak
            )
            # Note: The 'stream_to_file' method has a DeprecationWarning, but it works
            audio_response.stream_to_file(save_path)
            return f"Audio file successfully saved to {save_path}"
        except Exception as e:
            return f"Error generating audio: {e}"

# Instantiate the tools so our agents can use them
visual_tool = VisualTools()
audio_tool = AudioTools()

# Cell 4: Create Your Agents (Corrected)
visual_describer = Agent(
    role='Visual Describer',
    goal='Create brief, standard, and detailed accessibility descriptions for an image.',
    backstory=(
        'You are an expert in web accessibility and image analysis. '
        'You follow W3C WAI guidelines to create clear and useful descriptions for visually impaired users.'
    ),
    tools=[visual_tool],
    verbose=True,
    allow_delegation=False
)

audio_producer = Agent(
    role='Audio Producer',
    goal='Convert text descriptions into natural, high-quality audio files.',
    backstory=(
        'You are a professional voice actor with a clear and engaging voice. '
        'You use cutting-edge text-to-speech technology to produce audio that is easy to understand.'
    ),
    tools=[audio_tool],
    verbose=True,
    allow_delegation=False
)

# Cell 5: Define The Tasks
description_task = Task(
    description=(
        'Analyze the image located at {image_path}. '
        'Use your tool to generate the brief, standard, and detailed descriptions.'
    ),
    expected_output='A single string containing all three descriptions (brief, standard, detailed).',
    agent=visual_describer
)

audio_task = Task(
    description=(
        'Take the text output from the description task and convert it into a single audio file. '
        'Save the file as "module_1_output.mp3".'
    ),
    expected_output='A confirmation string stating the audio file has been saved, including the file path.',
    agent=audio_producer,
    context=[description_task]  # <-- This is CRUCIAL! It makes this task wait for the first one.
)

# Cell 6: Upload Image
from google.colab import files
from IPython.display import Image, Audio

print("Please upload an image to be processed by the Crew:")
uploaded = files.upload()

if not uploaded:
    print("No file uploaded. Please run the cell again.")
else:
    # Get the filename of the uploaded image
    image_path = list(uploaded.keys())[0]
    print(f"Image '{image_path}' uploaded.")
    display(Image(image_path, width=300))

# Cell 7: Crew!
if 'image_path' in locals():
    # Setup the crew
    accessibility_crew = Crew(
        agents=[visual_describer, audio_producer],
        tasks=[description_task, audio_task],
        process=Process.sequential, # Ensures tasks run one after another
        verbose=True # <-- This is the fix. Changed from 2 to True
    )

    # Kick off the crew with the image path as input
    print("\n--- Kicking off Accessibility Crew ---")
    crew_result = accessibility_crew.kickoff(inputs={'image_path': image_path})

    print("\n--- Crew Finished ---")
    print("Final Result:")
    print(crew_result)

    # Display the final audio output
    print("\nPlaying final audio output:")
    display(Audio("module_1_output.mp3"))

else:
    print("\nPlease run Cell 6 to upload an image first.")