# -*- coding: utf-8 -*-
"""Text-to-Sign Language.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1st-FzzTQ6N-dywZHSMBBKlnyRoeEXvMI
"""


# Cell 2: Imports & API Key
import os
from openai import OpenAI
from google.colab import userdata
from crewai import Agent, Task, Crew, Process
from crewai.tools import BaseTool
from IPython.display import Markdown

# --- Setup: Get API Key from Colab Secrets ---
try:
    OPENAI_API_KEY = userdata.get('OPENAI_API_KEY')
    os.environ['OPENAI_API_KEY'] = OPENAI_API_KEY
    client = OpenAI(api_key=OPENAI_API_KEY)
    print("OpenAI API key loaded and environment set.")
except Exception as e:
    print(f"Error loading API key: {e}")

# Cell 3: Define Custom Tools
class ASLGrammarTool(BaseTool):
    name: str = "ASL Grammar Conversion Tool"
    description: str = "Takes an English sentence and converts it into the correct ASL grammatical structure (e.g., Topic-Comment, removing articles)."

    def _run(self, english_text: str) -> str:
        print(f"--- Tool: Converting '{english_text}' to ASL grammar... ---")
        system_prompt = """
        You are an expert ASL linguist. Your job is to translate English sentences
        into the correct ASL grammatical structure.

        Key rules to follow:
        1.  **Topic-Comment:** The main topic of the sentence comes first. (e.g., "STORE, I GO-TO")
        2.  **No Articles:** Remove 'a', 'an', 'the'.
        3.  **No 'be' verbs:** Remove 'am', 'is', 'are'.
        4.  **Use Infinitives:** Use the base verb.
        5.  **Time:** Time indicators (like "YESTERDAY", "NOW") come first.

        Example:
        - English: "I am going to the store tomorrow."
        - ASL Grammar: "TOMORROW, STORE, I GO-TO."

        Respond with *only* the ASL grammar string and nothing else.
        """

        try:
            response = client.chat.completions.create(
                model="gpt-4o",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": english_text}
                ],
                max_tokens=100
            )
            asl_grammar_string = response.choices[0].message.content
            # Often the model returns words separated by commas, let's process it.
            # We'll split by comma, trim spaces, and join. This gives us a list of "signs".
            signs = [sign.strip() for sign in asl_grammar_string.split(',')]
            # We return this as a list of signs for the next agent
            return signs
        except Exception as e:
            return f"Error in grammar conversion: {e}"

class SignLookupTool(BaseTool):
    name: str = "Sign Description Lookup Tool"
    description: str = "Takes a single ASL sign word (e.g., 'STORE') and returns a brief textual description of how to perform that sign. Pretends to look it up in a sign database."

    def _run(self, sign_word: str) -> str:
        print(f"--- Tool: Looking up sign description for '{sign_word}'... ---")
        system_prompt = f"""
        You are a sign language dictionary.
        Given a single ASL sign word, provide a very brief, one-sentence
        description of how to perform the sign.

        Example:
        - Input: "STORE"
        - Output: "With both hands in 'S' shape, tap fingertips together twice."

        Input: "{sign_word}"
        Output:
        """

        try:
            response = client.chat.completions.create(
                model="gpt-4o",
                messages=[{"role": "system", "content": system_prompt}],
                max_tokens=100
            )
            description = response.choices[0].message.content.strip()
            return f"**{sign_word}**: {description}"
        except Exception as e:
            return f"Error looking up sign: {e}"

# Instantiate the tools
grammar_tool = ASLGrammarTool()
lookup_tool = SignLookupTool()

# Cell 4: Create Your Agents
asl_grammar_agent = Agent(
    role='ASL Grammar Translator',
    goal='Convert spoken English sentences into the correct ASL grammatical sign order.',
    backstory=(
        'You are an expert linguist specializing in the translation of English to '
        'American Sign Language. You understand the nuances of Topic-Comment structure, '
        'time-first rules, and the omission of articles and "be" verbs.'
    ),
    tools=[grammar_tool],
    verbose=True,
    allow_delegation=False
)

sign_sequencer_agent = Agent(
    role='Sign Language Sequencer',
    goal='Take a list of ASL-grammar signs and find the textual description for each one.',
    backstory=(
        'You are a sign language interpreter. Your job is not to translate, but to '
        'take a pre-translated list of ASL signs and provide a step-by-step '
        'description of how to perform each sign in sequence.'
    ),
    tools=[lookup_tool],
    verbose=True,
    allow_delegation=False # This agent will call its tool multiple times
)

# Cell 5: Define The Tasks
# This is the English sentence we want to translate
english_input = "I am going to the store."

# Task 1: Convert English to ASL Grammar
grammar_task = Task(
    description=f"Translate the following English sentence into ASL grammar: '{english_input}'",
    expected_output="A Python list of ASL sign words in the correct grammatical order (e.g., ['STORE', 'I', 'GO-TO']).",
    agent=asl_grammar_agent
)

# Task 2: Get descriptions for each sign
# This task is more complex. We tell the agent to iterate over the list from the first task.
sequence_task = Task(
    description=(
        "You have received a list of ASL sign words from the grammar agent. "
        "Your job is to use your 'Sign Description Lookup Tool' **one time for each sign** in the list. "
        "Compile all the descriptions into a single, numbered list."
    ),
    expected_output="A final, numbered list of sign descriptions.",
    agent=sign_sequencer_agent,
    context=[grammar_task] # <-- Waits for the grammar_task to finish
)

# Cell 6: Run Your Crew!
# Setup the crew
sign_language_crew = Crew(
    agents=[asl_grammar_agent, sign_sequencer_agent],
    tasks=[grammar_task, sequence_task],
    process=Process.sequential,
    verbose=False # Set to False to avoid logging recursion errors
)

# Kick off the crew
print("\n--- Kicking off Sign Language 'Brain' Crew ---")
crew_result = sign_language_crew.kickoff()

print("\n--- Crew Finished ---")
print("\n--- Final Sign Language Instructions ---")
# The final result will be in the .raw attribute
if crew_result and crew_result.raw:
    display(Markdown(crew_result.raw))
else:
    print(f"An error occurred: {crew_result}")